[package]
name = "enc-dec-service"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.0"
aes = "0.7.4"
block-modes = "0.8.1"
rand = "0.8.4"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

